### ISSUE TITLE
Uncaught RuntimeError: unreachable

### ISSUE THREAD

**Issue by damnitrahul** [LottieFiles/dotlottie-web#372]
## Overview
Hi there, I'm using `lottiefiles/dotlottie-react@0.8.8` and it's causing the entire page to freeze up throwing this error. 
Sometimes I get an error `Uncaught` sometimes it's `Uncaught RuntimeError: unreachable`. There are no logs apart from it which might help figure out the issue here. I'm unsure if this is a bug withing the lib or my component. 

This is happening with `0.8.8` as well as the latest `0.9.1` in development & production in both environments. 

```
Uncaught RuntimeError: unreachable
    at dotlottie-player.wasm:0xc3cde
    at dotlottie-player.wasm:0x2704d
    at dotlottie-player.wasm:0xf24af
    at dotlottie-player.wasm:0xececb
    at DotLottiePlayer.requestFrame (d0272cb2-cdf38b08bff01206.js:1:12251)
    at I._draw (d0272cb2-cdf38b08bff01206.js:1:41755)
```

## How to recreate
- Go to speechify.com
- Scroll down to the Lottie animation
- Reload page - page should freeze.  As far as I can tell, this only happens when you reload the page while Lottie is in view. 

## Screenshots
![Screenshot 2024-10-18 at 10 40 25 AM](https://github.com/user-attachments/assets/87a522fe-7f84-4dc3-a08d-d81ac1d30520)
![Screenshot 2024-10-18 at 10 39 54 AM](https://github.com/user-attachments/assets/22a14272-061c-4cff-9285-4634765d493c)

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@damnitrahul can you share with me the .lottie/lottie animation file ?

**Comment by theashraf** [comment]
@damnitrahul kindly check again the latest dotlottie-react@0.10.1 release, i think it fixes this issue, you can try to test out the animation on https://lottiefiles.github.io/dotlottie-web/ for quick verification

**Comment by theashraf** [comment]
Closing this one. Feel free to reopen it if the issue still persists
